title: Zihao (Klay) Lin # your name (or website title) here
logo: "/images/pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  M.S. Business Analytics@ <a href="https://merage.uci.edu/programs/masters/master-science-business-analytics/index.html">University of California, Irvine</a> |
  <br><br>
  B.S. Management Information@<a href="https://www.rit.edu/business/management-information-systems-bjtu">Rochester Institute of Technology</a> |
  <br><br>
  A human with love â¤ï¸
  <br><br>
  DubNationğŸ’™ğŸ’› Sports Enthusiast ğŸ€ Sunshine â˜€ï¸ Beach & Sea ğŸ–ï¸
  <br><br>
  <a href="https://www.linkedin.com/in/klay-lin-/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
